### ISSUE TITLE
[Feature request / idea] Freeze timestamp at the beginning of execution

### ISSUE THREAD

**Issue by nfreundlich** [fruch/pytest-elk-reporter#1]
Context:
- when executing tests in one test session, it is often useful to have a single view on the whole execution
- in current implementation, each test is uploaded with its exact timestamp

Issue/possible improvement:
- when creating a dashboard in Kibana from the results stored in ES, grouping together all tests from one execution is rather cumbersome
- using only one timestamp for the whole test set execution might solve this problem

My current workaround:
- In pytest_elk_reporter.py:
* ElkReporter.__init__: self.es_timestamp = datetime.datetime.utcnow().isoformat()
* ElkReporter. report_tests: timestamp=self.es_timestamp,#datetime.datetime.utcnow().isoformat()

**Comment by fruch** [comment]
that's a nice idea, but I would like to see it's optional. I think the default should be when the specific started to run.

**Comment by fruch** [comment]
Also feel free to open a PR, with such suggestion, also would love to hear the stories of how this project is being used.
