### ISSUE TITLE
[Feature request / idea] Report test tags to ES

### ISSUE THREAD

**Issue by nfreundlich** [fruch/pytest-elk-reporter#2]
Context:
- in test reporting, it is often useful to group tests according to their tags (as in @pytest.mark.performance, @pytest.mark.functional etc)

Possible improvement:
- report test tag(s) to ES by default

Remark:
- considering the possibility of multiple tags for one test may not be straightforward

**Comment by fruch** [comment]
This is a very good idea

In a former incarnation (proprietary version) of this plugin, it had this support. Would definitely add next time I'm hacking on this project.

Thank you
