### ISSUE TITLE
Configure output?

### ISSUE THREAD

**Issue by MaksymSofer** [fruch/pytest-elk-reporter#25]
Is there some way to change the format of data sent to elastic:

{'error': 0, 'passed': 0, 'failure': 0, 'skipped': 0, 'xfailed': 0, 'xpass': 0, 'passed & error': 0, 'failure & error': 0, 'skipped & error': 0, 'error & error': 0}

For example we want only Passed \ Errors + name of the test

**Comment by fruch** [comment]
what you mention here:
```
{'error': 0, 'passed': 0, 'failure': 0, 'skipped': 0, 'xfailed': 0, 'xpass': 0, 'passed & error': 0, 'failure & error': 0, 'skipped & error': 0, 'error & error': 0}
```
is just the summary, there is much more information per test that is sent out.

And no currently you can't control it (i.e. remove fields), but you can add information to it

**Comment by fruch** [comment]
@MaksymSofer is that answer you question ?

**Comment by MaksymSofer** [comment]
yes, but this did not resolved what we need
for pipeline we needed some way to reduce amount of data produced in output to make conditional checks.
but we found another solution (project closed and i do not remember what it was sadly)
