### ISSUE TITLE
python 3.4 build in windows fails cause of colorama

### ISSUE THREAD

**Issue by fruch** [fruch/pytest-elk-reporter#4]
```
ERROR: Package 'colorama' requires a different Python: 3.4.4 not in '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*'
```
https://ci.appveyor.com/project/fruch/pytest-elk-reporter/builds/29665084/job/m5o4y6j6x2ua7ro3

should consider removing python3.4 support....

**Comment by Formartha** [comment]
I think so as well..

**Comment by fruch** [comment]
remove python3.4 support
