### ISSUE TITLE
Not working with xdist

### ISSUE THREAD

**Issue by stevo2882** [fruch/pytest-elk-reporter#8]
When using this plugin with xdist I see the following AttributeError. The plugin is only being registered on the master node therefore there is no attribute request.config.pluginmanager.get_plugin("elk-reporter-runtime") on the slave nodes. To reproduce run tests with the xdist option.

`pytest /tests -n 4`

    @pytest.fixture(scope="session", autouse=True)
    def git_data(request):
        """
        Append git information into results session
        """
        git_info = dict()
        cmds = (
            ("git_commit_oneline", "git log --oneline  -1 --no-decorate"),
            ("git_commit_full", "git log -1 --no-decorate"),
            ("git_commit_sha", "git rev-parse HEAD"),
            ("git_commit_sha_short", "git rev-parse --short HEAD"),
            ("git_branch", "git rev-parse --abbrev-ref HEAD"),
            ("git_repo", "git config --get remote.origin.url"),
        )
        for key, command in cmds:
            try:
                git_info[key] = (
                    subprocess.check_output(command, shell=True).decode("utf-8").strip()
                )
            except subprocess.CalledProcessError:
                pass
        elk = request.config.pluginmanager.get_plugin("elk-reporter-runtime")
        elk.session_data.update(**git_info)
        AttributeError: 'NoneType' object has no attribute 'session_data'`

**Comment by fruch** [comment]
thank @stevo2882, 

this is an area I know I didn't tested. (i.e. xdist)
sorry for not writing that clearly (I know that to begin with), 
sorry that I didn't noticed this issue either.

I'm starting to use this soon in a project that xdist might be important for, so stay tuned, I might try to address it.

**Comment by fruch** [comment]
After test this a bit, seem like this is broken only on python2.7 and pypy, on python3 it works as expected,
can you supply a bit more details ? on where did you run it ?

**Comment by fruch** [comment]
I'll dig a little, if it's python 2.7 only issue, I'm not sure I'll try fixing it.

**Comment by fruch** [comment]
It seems to be working nicely across all python 3 versions, closing this
